### ISSUE TITLE
Align several cursor per line

### ISSUE THREAD

**Issue by matklad** [yo1dog/vscode-cursor-align#11]
Inspired by https://bytes.zone/posts/aligning-markdown-tables-in-helix/

If I have a text like this:

```
| ID | Name | Category ID |
|-|-|-|
| 11092 | Gorilla Fist | 27 |
| 11212 | Plate 3 x 3 | 14 |
| 11209 | Tyre 21 x 9.9 | 29 |
| 11640pr0003 | ELECTRIC GUITAR SHAFT Ø3.2 NO. 3 | 27 |
```

and I select all `|` (there are four per line), I want to be able to align all of them. Right now, only the last cursor per line is aligned. 

That is, I imagine the following iterative logic:

* Align the letfmost cursors on each line
* Then align the second leftmost cursors
* etc (it's OK if some line has fewer cursors, we just stop processing of this line)

**Comment by yo1dog** [comment]
Interesting. I like the idea. The extension kind of already does this with selections, which is analogous to 2 cursors per line as you observed.

This would be a change in both implementation and methodology and could be a breaking change for some users. But I expect that to be very rare given the current behavior and because the docs explicit state that multiple cursors per line "don't make much sense."

I will look into it.

**Comment by yo1dog** [comment]
Multi-column support (aligning multiple selections per line) has been released in V2.
