### ISSUE TITLE
Aligns incorrectly when the number of tabs varies between lines

### ISSUE THREAD

**Issue by staplerfahrer** [yo1dog/vscode-cursor-align#13]
To reproduce, create two lines: one without tabs in front of it, one with tabs:

abc x
(tab)abc x

now select the x-es, and ctrl+a

they will not align. It's like the plugin doesn't know or care about the width of a tab.

**Comment by adrianstephens** [comment]
I've also been experiencing this problem and made a fix.
I tried creating a PR, but I got a permission error. Probably my fault because I am hopeless with git.
But I see a PR languishing from 4 years ago, so wanted to see if you are open to them?
Meanwhile, if anyone would like to try my fix, unzip the attached file and overwrite the extension.js at 
%USERPROFILE%\.vscode\extensions\yo1dog.cursor-align-1.1.2
[extension.zip](https://github.com/user-attachments/files/16616776/extension.zip)

**Comment by yo1dog** [comment]
Correct. Tabs and other characters (code points) of undefined width (emojis, grapheme clusters, etc) are not supported for the reasons described here: https://github.com/yo1dog/vscode-cursor-align/issues/4#issuecomment-779244423

There is simply no way to know how many columns any given character spans. The best we can do is assume every character spans one column. See this vscode issue: https://github.com/microsoft/vscode/issues/100730

For example, this emoji 👨‍👩‍👦‍👦 is actually 7 characters: U+1F468 U+200D U+1F469 U+200D U+1F466 U+200D U+1F466. In vscode, placing the cursor after this emoji advances the column by 7, indicating that the column span should be 7. However, visually the emoji spans about 2.2 columns. The Japanese Kanji for man 男 is a single character (U+7537) and advances the cursor 1 column but visually spans about 1.9 columns.
![image](https://github.com/user-attachments/assets/9c6c381c-5916-425b-bab1-ff9a978354f6)

Tabs may be the one exception because the column span is explicitly defined by the vscode `editor.tabSize` setting and thus can be derived based on the tab character's starting column position. Specifically: `tabSize - ((col-1) % tabSize)`

Still, I am hesitant to support this because:
1. Mixing tab and space indention is generally not a good idea.
2. It's ambiguous if tabs or spaces should be used to align text.
3. This extension benefits from its simplicity and this change introduces an entirely new problem domain.

For example, take the following situation. We want to align A,B,C,D and tab width is 4. All of these are reasonable but conflicting expectations:
```
A
→   ••B
→   X•C
→   →   Y•••••D

1. Only spaces:
••••••••••••••A
→   ••••••••••B
→   X•••••••••C
→   →   Y•••••D

2. Prefer tabs:
→   →   →   ••A
→   ••→ →   ••B
→   X•→ →   ••C
→   →   Y•••••D

3. Replace contiguous spaces with tabs:
→   →   →   ••A
→   →   →   ••B
→   X→  →   ••C
→   →   Y•••••D
```

**Comment by yo1dog** [comment]
After some further thought, I think we could do this without necessarily opening Pandora's box. Keep it simple: calculate tab character column spans, only use spaces for alignment, and continue to assume all other characters span one column.

Tab column span calculation would be necessary to support this suggestion anyway: https://github.com/yo1dog/vscode-cursor-align/issues/8

I will look into it.

**Comment by staplerfahrer** [comment]
I feel that's most reasonable: honor the tab width, but use spaces. Tabs on
the left, spaces for any other type of alignment because that makes sense
within sentences as well. I feel for people who have to use emojis or
variable width characters in code but I kind of feel that this is a burden
on the developer and how they can maybe put those characters somewhere
else. Like stuff them all together in one block and leave them out of the
rest of your statements.

I have thought about the use of tabs a lot, and while mixing them is an
issue, if there's text in between I feel that it's not mixed. My go-to
argument has always been that the tab key was invented on typewriters
exactly for the purpose of tabulating data into columns. So if consistent
indentation is wanted, tabs are your guy. Like in code blocks. Aligning
equal signs for a list of variables doesn't require a 2-space, or 4-space
alignment and it's probably not wanted either in order to reduce line
length.

**Comment by yo1dog** [comment]
Added to V2.

**Edit:** Oops. Wrote the wrong comment on the wrong issue!

vscode's tab width setting is now respected.

This became a bit more complicated than I thought when mixed with multi-column mode. As I say in the comments:

>Because the size of tabs is variable based on its position, and its position can change during alignment, its size can change during alignment, and thus the size of a table column can not be known until we know the starting position of the table column, which can not be known until we know the starting position and size of each previous column.
>
>Thus, supporting tabs requires itterating blocks thrice rather than just once: The first time to group into table columns. Then in left-to-right order for each column, a second time to calculate the starting position of the column, and a thrid time to calcualte the colspan of the column.

However this was also necessary for implementing alignment using tabs instead of spaces. More details on that feature request: https://github.com/yo1dog/vscode-cursor-align/issues/8#issuecomment-2440120591 and in the commit: https://github.com/yo1dog/vscode-cursor-align/commit/79e6f65dd6a7d8be7512e5ba5b03c1f798248364
