### ISSUE TITLE
Feature-request :: Align with tabs instead of spaces

### ISSUE THREAD

**Issue by N247S** [yo1dog/vscode-cursor-align#8]
Quite simply put. Would it be possible to add the option to align with tabs instead of spaces?

assuming the 'tab-width in spaces' is available in a vs-code plugin, I would imagine it being possible.

**Comment by whatsupbros** [comment]
I would say the indentation character chosen by the user in VS Code itself should also be used by the extension.

**Comment by huntran-clgx** [comment]
check out my fork here: https://github.com/huntertran/vscode-cursor-align-with-tabs

**Comment by yo1dog** [comment]
I can see this. A command to align all cursors to the furthest tab stop by inserting tabs. Should be pretty simple. I'll look into it.

**Comment by yo1dog** [comment]
Added to V2.

Made a very simple rule: When aligning with tabs, the start and end of all sections/alignments will align with tab stops. I think this covers all uses cases nicely.

However, there are some cases in which it seems like unnecessary tabs are inserted. For example, if your tab width is set to 4, and you were to select text blocks all 3 characters in length, you may not expect a tab to be inserted at the end of every selection because they all already have the same length. However, a tab is inserted as one more character is needed in order to be aligned with a tab stop of 4.

I considered adding special exceptions to that rule: Namely that if no alignment needs to occur, no tabs should be inserted. Meaning if the starts of the sections are already aligned, don't add any tabs even if the start is not at a tab stop. And if the lengths of the sections are already equal, don't add any tabs to the end even if the end is not at a tab stop.

However, in practice this did not work will in multi-column mode when there can be an expectation that everything selected should be aligned in tab stops.

In general, it makes the rules more complicated and seemed to make the output more unpredictable.
